
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePDFReport = (injections, user, dateRange = 'all') => {
    const doc = new jsPDF();
    const userName = user?.user_metadata?.full_name || user?.email || 'User';
    const reportDate = new Date().toLocaleDateString();

    // Header
    // Logo placeholder or Title
    doc.setFontSize(22);
    doc.setTextColor(40, 44, 52);
    doc.text('PeptideLog Report', 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${reportDate}`, 14, 28);
    doc.text(`Patient/User: ${userName}`, 14, 33);

    if (dateRange !== 'all') {
        doc.text(`Period: ${dateRange}`, 14, 38);
    }

    // Summary Stats
    const totalInjections = injections.length;
    const uniquePeptides = [...new Set(injections.map(i => i.peptide_name))].join(', ');

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 45, 196, 45); // horizontal line

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Summary', 14, 55);

    doc.setFontSize(10);
    doc.text(`Total Injections: ${totalInjections}`, 14, 62);
    doc.text(`Active Compounds:`, 14, 68);

    // Wrap text for peptides list
    const splitPeptides = doc.splitTextToSize(uniquePeptides, 170);
    doc.text(splitPeptides, 45, 68);

    const statsEndY = 68 + (splitPeptides.length * 5);

    // Table
    const tableColumn = ["Date", "Time", "Peptide", "Dosage", "Notes"];
    const tableRows = [];

    injections.forEach(injection => {
        const date = new Date(injection.injection_date).toLocaleDateString();
        const time = new Date(injection.injection_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        const peptide = injection.peptide_name;
        const dosage = `${injection.dosage_mcg} mcg`;
        const notes = injection.notes || '-';

        tableRows.push([date, time, peptide, dosage, notes]);
    });

    doc.autoTable({
        startY: statsEndY + 10,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] }, // Indigo-600 match
        styles: { fontSize: 9, cellPadding: 3 },
        alternateRowStyles: { fillColor: [245, 247, 250] }
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by PeptideLog', 14, doc.internal.pageSize.height - 10);
        doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
    }

    doc.save(`peptide-report-${new Date().toISOString().split('T')[0]}.pdf`);
};
