import React, { useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { Share2, Download, Layers, ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useSchedule } from '../hooks/useSchedule';
import styles from './StackShareCard.module.css';

const StackShareCard = () => {
    const cardRef = useRef(null);
    const { user } = useAuth();
    const { templates } = useSchedule();
    const [generating, setGenerating] = useState(false);

    // Filter templates to get unique peptides in the stack
    const stackItems = templates.filter(t => t.isActive);

    // If no stack, don't show (or show empty state)
    if (!stackItems || stackItems.length === 0) {
        return null;
    }

    const handleDownload = async () => {
        if (!cardRef.current) return;
        setGenerating(true);

        try {
            const canvas = await html2canvas(cardRef.current, {
                scale: 2, // Retinas display
                backgroundColor: null, // Transparent background if possible
                logging: false,
                useCORS: true
            });

            const image = canvas.toDataURL('image/png');
            const link = document.createElement('a');
            link.href = image;
            link.download = `my-peptide-stack-${new Date().toISOString().split('T')[0]}.png`;
            link.click();
        } catch (error) {
            console.error('Error generating stack card:', error);
        } finally {
            setGenerating(false);
        }
    };

    const userName = user?.user_metadata?.full_name?.split(' ')[0] || 'My';

    return (
        <div className={styles.container}>
            <div className={styles.header}>
                <h3><Share2 size={18} /> Share Your Stack</h3>
                <button
                    onClick={handleDownload}
                    disabled={generating}
                    className={styles.downloadBtn}
                >
                    <Download size={16} />
                    {generating ? 'Generating...' : 'Save Image'}
                </button>
            </div>

            {/* The Card Capture Area */}
            <div className={styles.cardWrapper} ref={cardRef}>
                <div className={styles.card}>
                    <div className={styles.cardHeader}>
                        <div className={styles.brand}>
                            <Layers size={24} color="#10b981" />
                            <span>PeptideLog</span>
                        </div>
                        <div className={styles.date}>
                            {new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}
                        </div>
                    </div>

                    <h2 className={styles.title}>{userName}'s Protocol</h2>

                    <div className={styles.stackGrid}>
                        {stackItems.map((item, index) => (
                            <div key={item.id || index} className={styles.stackItem}>
                                <div className={styles.itemHeader}>
                                    <span className={styles.peptideName}>{item.peptide}</span>
                                    <ShieldCheck size={14} className={styles.verifiedIcon} />
                                </div>
                                <div className={styles.itemDetails}>
                                    <span className={styles.dosage}>
                                        {item.dosage} {item.unit}
                                    </span>
                                    <span className={styles.schedule}>
                                        {item.recurrenceDays?.length === 7
                                            ? 'Daily'
                                            : `${item.recurrenceDays?.length}x / week`
                                        }
                                    </span>
                                </div>
                            </div>
                        ))}
                    </div>

                    <div className={styles.cardFooter}>
                        <span>Generated by PeptideLog.net</span>
                    </div>
                </div>
            </div>

            <p className={styles.hint}>
                Download this card to share on Instagram Stories or Twitter!
            </p>
        </div>
    );
};

export default StackShareCard;
