INSERT INTO public.peptides (
    name, 
    category, 
    half_life_hours, 
    description, 
    benefits, 
    side_effects, 
    warnings, 
    dosage_protocols,
    common_dosage,
    research_links
) VALUES 
(
    'Semaglutide',
    'GLP-1 Agonist',
    168,
    'A GLP-1 receptor agonist primarily used for weight loss and blood sugar management.',
    ARRAY['Significant weight loss (10-15% body weight)','Improved blood sugar control','Reduced appetite and food cravings','Cardiovascular benefits','Improved insulin sensitivity','Potential neuroprotective effects'],
    ARRAY['Nausea (especially when starting)','Vomiting','Diarrhea or constipation','Abdominal pain','Fatigue','Headache','Dizziness'],
    ARRAY['Risk of thyroid C-cell tumors (animal studies)','Pancreatitis risk','Gallbladder problems','Kidney problems in rare cases','Not for type 1 diabetes','Contraindicated with personal/family history of medullary thyroid carcinoma'],
    '[{"name":"Standard Weight Loss Protocol","level":"Beginner to Advanced","description":"FDA-approved escalation schedule for weight management","schedule":[{"week":"1-4","dose":"0.25mg","frequency":"Once weekly","notes":"Titration phase - minimize side effects"},{"week":"5-8","dose":"0.5mg","frequency":"Once weekly","notes":"Continue if tolerating well"},{"week":"9-12","dose":"1mg","frequency":"Once weekly","notes":"Therapeutic dose for many users"},{"week":"13-16","dose":"1.7mg","frequency":"Once weekly","notes":"Optional escalation"},{"week":"17+","dose":"2.4mg","frequency":"Once weekly","notes":"Maximum dose"}],"duration":"16-20 weeks minimum","notes":"Stay at each dose for at least 4 weeks. Only increase if weight loss plateaus and side effects are minimal."},{"name":"Maintenance Protocol","level":"Maintenance","description":"After reaching goal weight","schedule":[{"week":"Ongoing","dose":"0.5-1mg","frequency":"Once weekly","notes":"Lowest effective dose"}],"duration":"Long-term","notes":"Find minimum dose that maintains weight loss. Some users cycle off for 4-8 weeks periodically."}]'::jsonb,
    '0.25mg - 2.4mg weekly',
    ARRAY['https://www.nejm.org/doi/full/10.1056/NEJMoa2032183','https://pubmed.ncbi.nlm.nih.gov/33567185/']
),
(
    'Tirzepatide',
    'Dual GIP/GLP-1 Agonist',
    120,
    'A dual GIP and GLP-1 receptor agonist showing superior weight loss compared to semaglutide.',
    ARRAY['Superior weight loss (15-22% body weight)','Excellent blood sugar control','Improved lipid profiles','Reduced cardiovascular risk','Better appetite suppression than GLP-1 alone','Improved insulin sensitivity'],
    ARRAY['Nausea and vomiting','Diarrhea','Decreased appetite','Constipation','Indigestion','Fatigue'],
    ARRAY['Similar thyroid tumor risk as semaglutide','Pancreatitis risk','Hypoglycemia when combined with insulin','Gallbladder disease','Acute kidney injury in dehydrated patients'],
    '[{"name":"Escalation Protocol","level":"Beginner","description":"Standard FDA titration","schedule":[{"week":"1-4","dose":"2.5mg","frequency":"Once weekly","notes":"Starter dose"},{"week":"5-8","dose":"5mg","frequency":"Once weekly"},{"week":"9-12","dose":"7.5-10mg","frequency":"Once weekly","notes":"Advance if tolerated"},{"week":"13+","dose":"12.5-15mg","frequency":"Once weekly","notes":"Max dose"}],"duration":"Ongoing","notes":"Hold dose increases if GI effects persist."}]'::jsonb,
    '2.5mg - 15mg weekly',
    ARRAY['https://www.nejm.org/doi/full/10.1056/NEJMoa2107519']
),
(
    'Liraglutide',
    'GLP-1 Agonist',
    13,
    'Daily GLP-1 analog used for diabetes and chronic weight management.',
    ARRAY['Weight loss and appetite control','Improved glycemic control','Cardiovascular risk reduction','Daily dosing allows quick titration changes'],
    ARRAY['Nausea','Vomiting','Diarrhea or constipation','Injection site pain'],
    ARRAY['Thyroid C-cell tumor warning','Pancreatitis risk','Gallbladder disease'],
    '[{"name":"Weight Management Titration","level":"Beginner","description":"Standard Saxenda titration","schedule":[{"week":"1","dose":"0.6mg","frequency":"Daily"},{"week":"2","dose":"1.2mg","frequency":"Daily"},{"week":"3","dose":"1.8mg","frequency":"Daily"},{"week":"4","dose":"2.4mg","frequency":"Daily"},{"week":"5+","dose":"3.0mg","frequency":"Daily","notes":"Maintenance/max"}],"duration":"Ongoing","notes":"Hold or reduce dose if GI side effects persist."}]'::jsonb,
    '0.6mg - 3.0mg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/20573918/']
),
(
    'Dulaglutide',
    'GLP-1 Agonist',
    120,
    'Once-weekly GLP-1 analog used for glycemic control with modest weight loss.',
    ARRAY['Improved glycemic control','Cardiovascular risk reduction data','Convenient weekly dosing'],
    ARRAY['Nausea','Diarrhea','Vomiting','Abdominal pain'],
    ARRAY['Thyroid C-cell tumor warning','Pancreatitis risk','Gallbladder disease'],
    '[]'::jsonb,
    '0.75mg - 4.5mg weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/24550040/']
),
(
    'Retatrutide',
    'Triple Agonist (GLP-1/GIP/Glucagon)',
    5,
    'Triple incretin/agonist in trials showing substantial weight loss.',
    ARRAY['Very high weight loss in trials','Multi-pathway metabolic effects','Weekly dosing'],
    ARRAY['GI effects similar to GLP-1s','Potential heart rate increase','Injection site reactions'],
    ARRAY['Pancreatitis risk theoretical','May affect heart rate','Thyroid C-cell tumor warning anticipated'],
    '[]'::jsonb,
    '1-12mg weekly (trial ranges)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/37397207/']
),
(
    'BPC-157',
    'Healing Peptide',
    4,
    'A synthetic peptide derived from a protective protein found in stomach acid, known for healing properties.',
    ARRAY['Accelerated wound healing','Tendon and ligament repair','Muscle healing','Gut healing (leaky gut, IBS)','Reduced inflammation','Joint pain relief','Neuroprotective effects','Improved blood flow'],
    ARRAY['Generally well-tolerated','Occasional fatigue','Dizziness (rare)','Nausea (rare)','Headache (rare)'],
    ARRAY['Limited human clinical trials','Long-term safety unknown','May affect blood pressure','Consult doctor if on blood thinners'],
    '[]'::jsonb,
    '250-500mcg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/31633635/','https://pubmed.ncbi.nlm.nih.gov/32568251/']
),
(
    'TB-500 (Thymosin Beta-4)',
    'Healing Peptide',
    120,
    'A synthetic version of Thymosin Beta-4, promoting healing and recovery.',
    ARRAY['Enhanced tissue repair','Reduced inflammation','Improved flexibility','Faster injury recovery','Hair growth promotion','Cardiovascular protection','Neuroprotection'],
    ARRAY['Minimal side effects reported','Possible headache','Lethargy','Temporary flushing'],
    ARRAY['Banned by WADA for athletes','Limited long-term human studies','May promote cancer cell migration (theoretical)','Avoid if pregnant or breastfeeding'],
    '[]'::jsonb,
    '2-5mg twice weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/20709819/']
),
(
    'Ipamorelin',
    'Growth Hormone Secretagogue',
    2,
    'A selective growth hormone secretagogue that stimulates GH release without affecting cortisol.',
    ARRAY['Increased growth hormone production','Improved muscle mass','Enhanced fat loss','Better sleep quality','Improved skin elasticity','Faster recovery','Increased bone density','Anti-aging effects'],
    ARRAY['Water retention (mild)','Increased hunger','Tingling or numbness','Headache','Flushing'],
    ARRAY['May affect blood sugar levels','Not for use with active cancer','Consult doctor if diabetic','May interact with thyroid medications'],
    '[]'::jsonb,
    '200-300mcg 2-3 times daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/9849822/']
),
(
    'CJC-1295 (no DAC)',
    'Growth Hormone Releasing Hormone',
    0.5,
    'A GHRH analog that increases growth hormone and IGF-1 levels with short half-life.',
    ARRAY['Increased GH and IGF-1 levels','Muscle growth','Fat loss','Improved recovery','Better sleep','Enhanced immune function','Increased bone density'],
    ARRAY['Water retention','Joint pain','Carpal tunnel symptoms','Increased hunger','Numbness or tingling'],
    ARRAY['May worsen existing tumors','Affects blood sugar','Not for pregnant/nursing women','Regular blood work recommended'],
    '[]'::jsonb,
    '100-200mcg 2-3 times daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/16352683/']
),
(
    'CJC-1295 (DAC)',
    'Growth Hormone Releasing Hormone',
    168,
    'Long-acting GHRH analog with drug affinity complex (DAC) for extended half-life.',
    ARRAY['Sustained GH and IGF-1 elevation','Reduced injection frequency','Supports muscle gain and fat loss','Improved sleep quality','Potential immune support'],
    ARRAY['Water retention','Flu-like symptoms (rare)','Joint stiffness','Injection site irritation'],
    ARRAY['May worsen existing tumors','Monitor blood glucose and IGF-1','Not recommended during pregnancy','Use medical supervision for long protocols'],
    '[]'::jsonb,
    '1-2mg once weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/16352683/']
),
(
    'MK-677 (Ibutamoren)',
    'Growth Hormone Secretagogue',
    24,
    'An oral ghrelin mimetic that increases GH and IGF-1 without injections.',
    ARRAY['Oral dosing convenience','Increased GH/IGF-1 levels','Improved sleep depth','Appetite stimulation','Potential muscle gain and fat loss support'],
    ARRAY['Water retention','Increased appetite','Numbness/tingling','Transient insulin resistance','Lethargy in some users'],
    ARRAY['Monitor glucose and lipids','Avoid in active cancer','Not for pregnancy or nursing','Use caution with diabetes or insulin resistance'],
    '[]'::jsonb,
    '10-25mg orally daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/9430604/']
),
(
    'Melanotan II',
    'Melanocortin Agonist',
    1,
    'A synthetic analog of alpha-melanocyte stimulating hormone, used for tanning and libido enhancement.',
    ARRAY['Skin tanning without UV exposure','Increased libido','Potential appetite suppression','Erectile function improvement','Reduced sun damage risk'],
    ARRAY['Nausea (common initially)','Flushing','Increased libido (can be unwanted)','Darkening of moles and freckles','Yawning and stretching','Spontaneous erections'],
    ARRAY['Not FDA approved','May increase melanoma risk (theoretical)','Can darken existing moles','Permanent skin darkening possible','Cardiovascular effects possible'],
    '[]'::jsonb,
    '0.25-1mg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/16448591/']
),
(
    'PT-141 (Bremelanotide)',
    'Melanocortin Agonist',
    2.5,
    'A melanocortin receptor agonist for sexual dysfunction in men and women.',
    ARRAY['Improves libido in both sexes','Works independent of nitric oxide pathways','Rapid onset (within 30-60 minutes)','FDA-approved nasal form for female HSDD'],
    ARRAY['Nausea','Flushing','Headache','Transient blood pressure changes','Injection site irritation'],
    ARRAY['Avoid with uncontrolled hypertension','Not for pregnancy','Use caution with cardiovascular disease','Nasal formulation has specific dosing limits'],
    '[]'::jsonb,
    '1.25-1.75mg as needed',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/16034475/']
),
(
    'GHK-Cu (Copper Peptide)',
    'Healing & Anti-Aging',
    1,
    'A naturally occurring copper complex with powerful healing and anti-aging properties.',
    ARRAY['Wound healing acceleration','Collagen and elastin production','Skin rejuvenation','Hair growth stimulation','Anti-inflammatory effects','Antioxidant properties','Improved skin firmness','Reduced fine lines and wrinkles'],
    ARRAY['Minimal side effects','Possible skin irritation (topical)','Mild headache (rare)','Temporary redness at injection site'],
    ARRAY['Avoid if allergic to copper','May interact with copper supplements','Limited long-term studies','Consult doctor if on blood thinners'],
    '[]'::jsonb,
    '1-3mg 2-3 times weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/25607907/','https://pubmed.ncbi.nlm.nih.gov/28294172/']
),
(
    'AOD-9604',
    'Metabolic & Fat Loss',
    2,
    'A modified fragment of human growth hormone designed to promote fat loss without GH-related effects.',
    ARRAY['May enhance fat oxidation','Minimal impact on blood sugar','No significant effect on IGF-1','Generally mild side effect profile'],
    ARRAY['Headache (rare)','Mild nausea','Injection site redness'],
    ARRAY['Limited clinical validation','Avoid during pregnancy or nursing','Monitor for unexpected glucose changes'],
    '[]'::jsonb,
    '250-500mcg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/21869961/']
),
(
    'MOTS-c',
    'Metabolic & Mitochondrial',
    2,
    'A mitochondrial-derived peptide studied for metabolic regulation and exercise performance.',
    ARRAY['Improves insulin sensitivity (animal data)','Supports mitochondrial function','May enhance exercise performance','Potential anti-inflammatory effects'],
    ARRAY['Limited human data; side effects largely unknown','Mild fatigue reported anecdotally','Injection site irritation'],
    ARRAY['Use caution with metabolic disorders until more data emerges','Avoid during pregnancy','Monitor glucose if combining with other metabolic agents'],
    '[]'::jsonb,
    '10-20mg weekly (split doses)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/25622254/']
),
(
    'Selank',
    'Cognitive & Anxiolytic',
    0.5,
    'An anxiolytic peptide derived from tuftsin, studied for calming and cognitive effects.',
    ARRAY['Reduces anxiety without sedation (anecdotal)','May improve focus and memory','Supports immune modulation','Low risk of dependence'],
    ARRAY['Mild nasal irritation (if intranasal)','Headache','Fatigue in some users'],
    ARRAY['Limited long-term human data','Avoid use in pregnancy','Monitor for mood changes when combined with other nootropics'],
    '[]'::jsonb,
    '250-750mcg 1-3 times daily (nasal or subcutaneous)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/15862908/']
),
(
    'Semax',
    'Cognitive & Nootropic',
    0.5,
    'A synthetic ACTH(4-10) analog used in Russia for cognitive support and neuroprotection.',
    ARRAY['May enhance focus and memory','Neuroprotective properties (animal data)','Potential mood stabilization','Low systemic side effect burden'],
    ARRAY['Nasal irritation','Headache','Transient blood pressure increase (rare)'],
    ARRAY['Avoid during pregnancy','Use caution with uncontrolled hypertension','Limited long-term safety data'],
    '[]'::jsonb,
    '200-600mcg 1-3 times daily (nasal)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/9855565/']
),
(
    'Thymosin Alpha-1',
    'Immune Modulator',
    2,
    'Synthetic thymic peptide explored for immune modulation and antiviral support.',
    ARRAY['Supports immune response','Adjunct in some infections (regional use)','May aid vaccine response'],
    ARRAY['Injection site redness','Fatigue','Mild headache'],
    ARRAY['Use under medical supervision','Potential autoimmune considerations'],
    '[]'::jsonb,
    '1.6mg 2-3 times weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/31445021/']
),
(
    'Epithalon',
    'Longevity & Telomerase',
    20,
    'Tetrapeptide researched for potential telomerase activation and longevity effects.',
    ARRAY['Potential telomerase activation (animal data)','Sleep quality improvements (anecdotal)','Antioxidant activity'],
    ARRAY['Limited human data; generally mild','Injection site irritation','Occasional vivid dreams'],
    ARRAY['Long-term safety unknown','Use caution with hormone-sensitive conditions'],
    '[]'::jsonb,
    '5-10mg daily (short courses)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/15123323/']
),
(
    'SS-31 (Elamipretide)',
    'Mitochondrial Peptide',
    1,
    'A mitochondria-targeted peptide being studied for cardiomyopathy and mitochondrial disorders.',
    ARRAY['May improve mitochondrial function','Potential cardiac protective effects','Explored in ophthalmic formulations'],
    ARRAY['Injection site reactions','Headache','Nausea'],
    ARRAY['Use only under research/clinical supervision'],
    '[]'::jsonb,
    '5-10mg daily (trial-dependent)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/21465260/']
),
(
    'Cerebrolysin',
    'Neuropeptide Blend',
    NULL,
    'A porcine brain-derived peptide mixture used in some regions for cognitive and stroke recovery support.',
    ARRAY['Neuroprotective properties','Potential cognitive support','May aid stroke recovery'],
    ARRAY['Injection site pain','Dizziness','Headache'],
    ARRAY['Avoid in seizure disorders without clearance','Use medical supervision for IV/IM'],
    '[]'::jsonb,
    '5-10ml IV/IM daily (cycles)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/25644553/']
),
(
    'P21',
    'Nootropic Peptide',
    NULL,
    'A synthetic peptide derived from CNTF fragments, explored for neurotrophic effects.',
    ARRAY['Potential neurotrophic support (preclinical)','May aid cognitive function (anecdotal)'],
    ARRAY['Limited data; unknown long-term safety','Injection site irritation'],
    ARRAY['Research-only; insufficient human safety data'],
    '[]'::jsonb,
    '5-10mg weekly (anecdotal)',
    ARRAY[]::text[]
),
(
    'Follistatin 344',
    'Performance & Muscle',
    6,
    'A myostatin-binding protein fragment explored for muscle growth and recovery.',
    ARRAY['Potential increase in muscle mass','Supports recovery','May enhance strength gains','Synergistic with resistance training'],
    ARRAY['Injection site irritation','Possible GI discomfort','Unknown endocrine effects'],
    ARRAY['Not approved for human use','Potential impact on fertility and hormones unknown','Avoid if pregnant or breastfeeding'],
    '[]'::jsonb,
    '100-300mcg daily (short bursts)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/15345781/']
),
(
    'YK-11',
    'Performance & Muscle',
    6,
    'A myostatin-inhibiting SARM-like compound promoted for muscle growth.',
    ARRAY['Potential rapid strength gains','May inhibit myostatin pathways','Oral dosing convenience'],
    ARRAY['Joint pain','Liver strain potential','Hair shedding (androgenic)','Aggression or mood changes'],
    ARRAY['Hepatotoxicity risk—monitor liver enzymes','Not for women who are pregnant or breastfeeding','Prohormone/PCT considerations not well-studied'],
    '[]'::jsonb,
    '5-15mg orally daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/23118235/']
),
(
    'Sermorelin',
    'Growth Hormone Secretagogue',
    10,
    'A GHRH analogue used to diagnose and treat poor growth in children, and for anti-aging in adults.',
    ARRAY['Increases natural GH production','Improved sleep quality','Increased lean muscle mass','Reduced body fat','Faster recovery from exercise'],
    ARRAY['Injection site reactions','Flushing','Headache','Dizziness','Hyperactivity'],
    ARRAY['Avoid in active cancer','Monitor for potential insulin resistance','Not for pregnancy'],
    '[]'::jsonb,
    '200-500mcg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/18607233/']
),
(
    'Tesamorelin',
    'Growth Hormone Releasing Hormone',
    26,
    'A potent GHRH analogue specifically approved to reduce excess abdominal fat in HIV patients.',
    ARRAY['Significant reduction in visceral fat','Increases IGF-1 levels','Improves lipid profile','Cognitive benefits in some studies'],
    ARRAY['Joint pain','Injection site redness','Fluid retention','Muscle aches'],
    ARRAY['May increase blood sugar','Monitor IGF-1 levels','Avoid in active cancer'],
    '[]'::jsonb,
    '1-2mg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/20554796/']
),
(
    'Epitalon',
    'Anti-Aging & Longevity',
    NULL,
    'A synthetic pineal peptide known for its potential to lengthen telomeres and regulate circadian rhythms.',
    ARRAY['Telomere elongation (anti-aging)','Circadian rhythm regulation','Antioxidant effects','Improved sleep','Potential life extension (animal studies)'],
    ARRAY['None significantly reported','Possible mild fatigue'],
    ARRAY['Limited long-term safety data','Not for children or pregnancy'],
    '[{"name":"Standard Anti-Aging Cycle","level":"Intermediate","description":"Khavinson Protocol","schedule":[{"week":"1-2","dose":"5-10mg","frequency":"Daily","notes":"10-20 day course"}],"duration":"Repeat every 6-12 months","notes":"Short, high-dose courses are standard for this peptide."}]'::jsonb,
    '5-10mg daily (cycled)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/12937682/']
),
(
    'Thymalin',
    'Immune System',
    NULL,
    'A thymus-derived peptide bioregulator that supports immune function and T-cell differentiation.',
    ARRAY['Immune system restoration','Enhanced T-cell function','Potential anti-tumor effects (adjunct)','Reduced inflammation'],
    ARRAY['None significantly reported','Injection site irritation'],
    ARRAY['Consult doctor if you have autoimmune conditions','Not for pregnancy'],
    '[]'::jsonb,
    '10mg daily for 10 days',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/12577695/']
),
(
    'DSIP (Delta Sleep-Inducing Peptide)',
    'Neurological & Sleep',
    15,
    'A neuropeptide that promotes deep (delta) wave sleep and stress reduction.',
    ARRAY['Induces deep, restorative sleep','Reduces stress and cortisol','Potential pain relief','Normalization of blood pressure'],
    ARRAY['Grogginess upon waking (if dose too high)','Headache','Nausea (rare)'],
    ARRAY['Do not drive after administration','Start with low dose to assess tolerance'],
    '[]'::jsonb,
    '100mcg before bed',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/6548967/']
),
(
    'Foxo4-DRI',
    'Senolytic (Anti-Aging)',
    NULL,
    'A peptide designed to target and eliminate senescent ("zombie") cells to rejuvenate tissues.',
    ARRAY['Eliminates senescent cells','Improves tissue function','Coat condition improvement (mice)','Kidney function restoration (mice)'],
    ARRAY['Fatigue (during clearance)','Flu-like symptoms','Muscle aches'],
    ARRAY['Highly experimental','Clearance of too many cells at once can be stressful'],
    '[]'::jsonb,
    'Experimental protocols (e.g. 3-10mg/cycle)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/28340339/']
),
(
    'ARA-290 (Cibinetide)',
    'Healing & Neuropathy',
    NULL,
    'A non-hematopoietic EPO derivative designed to repair small nerve fibers and reduce neuropathic pain.',
    ARRAY['Small fiber neuropathy repair','Pain reduction','Anti-inflammatory','Improved HbA1c (some studies)'],
    ARRAY['Generally mild','Injection site reactions'],
    ARRAY['Monitor blood pressure','Limited long-term safety data'],
    '[]'::jsonb,
    '4mg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/25613020/']
),
(
    '5-Amino-1MQ',
    'Metabolic & Fat Loss',
    NULL,
    'Small molecule NNMT inhibitor that increases cellular NAD+ and metabolic rate.',
    ARRAY['Increased metabolic rate','Fat loss without CNS stimulation','Increases NAD+ levels','Muscle preservation'],
    ARRAY['Insomnia (if taken late)','Mild GI upset'],
    ARRAY['Don''t take before bed'],
    '[]'::jsonb,
    '50-150mg daily (Oral)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/29969636/']
),
(
    'NAD+ (Nicotinamide Adenine Dinucleotide)',
    'Cellular Energy & Anti-Aging',
    NULL,
    'A critical coenzyme found in every cell, essential for energy production (ATP) and DNA repair.',
    ARRAY['Increased energy and stamina','Improved mental clarity and focus','DNA repair support (PARP activation)','Anti-aging (sirtuin activation)','Addiction recovery support'],
    ARRAY['Nausea (common with rapid IV)','Flushing/Chest pressure (IV)','Headache','Fatigue initially'],
    ARRAY['Start low to assess tolerance','May interact with certain chemotherapy drugs'],
    '[]'::jsonb,
    '100-500mg (IV/IM/SubQ)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/29514064/']
),
(
    'Glutathione',
    'Antioxidant & Detox',
    10,
    'The body''s "master antioxidant," crucial for detoxification, immune function, and reducing oxidative stress.',
    ARRAY['Powerful antioxidant support','Liver detoxification','Skin brightening/lightening','Immune system boost','Reduced inflammation'],
    ARRAY['Rare allergic reactions','Lower zinc levels (long term)','Asthma exacerbation (inhaled form)'],
    ARRAY['Avoid if sulfite sensitive','Consult doctor if asthmatic'],
    '[]'::jsonb,
    '200-600mg daily or weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/21908948/']
),
(
    'Oxytocin',
    'Hormone & Wellness',
    3,
    'The "love hormone" involved in bonding, stress reduction, and sexual arousal.',
    ARRAY['Improved social bonding','Stress/Cortisol reduction','Enhanced orgasm/libido','Mood elevation'],
    ARRAY['Headache','Nausea','Uterine contractions (females)'],
    ARRAY['Do not use if pregnant (induces labor)','Monitor blood pressure'],
    '[]'::jsonb,
    '10-20IU (Nasal) or 5-10IU (SubQ)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/1601267/']
),
(
    'KPV',
    'Anti-Inflammatory & Gut',
    NULL,
    'A tripeptide (Lysine-Proline-Valine) derived from alpha-MSH, known for potent anti-inflammatory effects.',
    ARRAY['Potent anti-inflammatory','Gut health (IBD/IBS support)','Antimicrobial (Candida/Mold)','Skin health (Psoriasis/Eczema)','Non-hormonal (no tanning/libido effects)'],
    ARRAY['None significantly reported','Injection site irritation'],
    ARRAY['Consult doctor for autoimmune conditions'],
    '[]'::jsonb,
    '200-500mcg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/10504176/']
),
(
    'LL-37 (Cathelicidin)',
    'Antimicrobial & Immune',
    NULL,
    'A powerful antimicrobial peptide produced by the body to fight bacteria, viruses, and fungi.',
    ARRAY['Broad-spectrum antimicrobial','Biofilm disruptor','Wound healing','Immune modulation','Gut health support'],
    ARRAY['Herxheimer reaction (die-off)','Injection site pain/redness','Inflammation (if dose too high)'],
    ARRAY['Start very low to avoid Herx reaction','Avoid in autoimmune diseases (Lupus/RA) unless supervised'],
    '[]'::jsonb,
    '100mcg daily (cycled)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/17007963/']
),
(
    'Dihexa',
    'Nootropic & Cognitive',
    NULL,
    'A potent angiotensin IV analog derived peptide promoting synaptogenesis (brain connection growth).',
    ARRAY['Powerful neurogenesis','Cognitive enhancement','Memory repair','Stroke/TBI recovery potential'],
    ARRAY['Autism-like overstimulation (rare)','Irritability','Headache'],
    ARRAY['Monitor for cancerous growths (theoretical risk due to growth factors)','Do not combine with other potent growth agents'],
    '[]'::jsonb,
    '10-20mg Ora/Transdermal',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/23168565/']
),
(
    'IGF-1 LR3',
    'Growth & Muscle',
    20,
    'A long-acting analog of Insulin-like Growth Factor 1, potent for muscle growth and recovery.',
    ARRAY['Significant muscle hyperplasia','Enhanced recovery','Nutrient shuttling','Fat loss','Improved pumps'],
    ARRAY['Hypoglycemia (low blood sugar)','Gut distension ("GH gut") at high doses','Headache','Nausea'],
    ARRAY['Consume carbs post-injection','Avoid in active cancer','Do not use for long periods'],
    '[]'::jsonb,
    '20-50mcg daily (cycled)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/18607233/']
),
(
    'HGH Frag 176-191',
    'Fat Loss',
    NULL,
    'A fragment of the HGH molecule specifically isolated for its fat-burning properties without glycemic effects.',
    ARRAY['Targeted fat loss','No effect on blood sugar','No water retention','No effect on IGF-1 levels'],
    ARRAY['Injection site redness','Mild headache'],
    ARRAY['Ensure fasted state for efficacy'],
    '[]'::jsonb,
    '250-500mcg twice daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/11713213/']
),
(
    'Kisspeptin-10',
    'Hormone & Fertility',
    NULL,
    'A peptide that stimulates GnRH release, boosting testosterone and fertility without shutting down natural production.',
    ARRAY['Increased testosterone','Improved fertility/sperm quality','Libido enhancement','Alternative to HCG'],
    ARRAY['Flushing','Headache','Injection site pain'],
    ARRAY['Monitor hormone levels'],
    '[]'::jsonb,
    '100mcg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/16260654/']
),
(
    'VIP (Vasoactive Intestinal Peptide)',
    'Immune & CIRS',
    NULL,
    'A neuropeptide used primarily in the Shoemaker Protocol for mold toxicity and CIRS.',
    ARRAY['Reduces inflammation (CIRS)','Improves hormonal regulation','Supports brain health','Pulmonary hypertension support'],
    ARRAY['Low blood pressure','Palpitations','Headache','Flushing'],
    ARRAY['Monitor lipase levels','Monitor blood pressure'],
    '[]'::jsonb,
    '50mcg 4x daily (Nasal)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/23566056/']
),
(
    'Melanotan 1 (Afamelanotide)',
    'Melanocortin Agonist',
    NULL,
    'A synthetic analog of alpha-MSH that induces tanning with fewer side effects than Melanotan II.',
    ARRAY['Increased melanin production (tanning)','Photoprotection from UV damage','Less nausea/flushing than Melanotan II','Used for Erythropoietic Protoporphyria (EPP)'],
    ARRAY['Nausea (mild)','Flushing','Injection site reactions'],
    ARRAY['Monitor moles/freckles for changes','Not FDA approved as injectable'],
    '[]'::jsonb,
    '1-2mg daily (Injection)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/15056820/']
),
(
    'HGH Fragment 176-191',
    'Fat Loss',
    1,
    'A stabilized fragment of the GH molecule (C-terminus) that specifically targets fat loss (lipolysis) without affecting insulin or IGF-1.',
    ARRAY['Potent fat loss aid','No effect on blood glucose','No water retention','Does not impact IGF-1 levels'],
    ARRAY['Injection site redness','Rare feeling of flushing'],
    ARRAY['Ensure purity (often faked)','Avoid eating 2 hours before/after'],
    '[]'::jsonb,
    '250-500mcg twice daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/11713213/']
),
(
    'GHRP-6',
    'Growth Hormone Secretagogue',
    2,
    'A powerful GH secretagogue known for stimulating significant appetite and growth hormone release.',
    ARRAY['Increases Growth Hormone','Stimulates appetite (bulking)','Improved recovery','Anti-inflammatory'],
    ARRAY['Intense hunger','Water retention','Prolactin increase (dose dependent)','Cortisol increase (mild)'],
    ARRAY['Monitor prolactin','Monitor blood glucose'],
    '[]'::jsonb,
    '100-200mcg 3x daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/8492102/']
),
(
    'GHRP-2 (Pralmorelin)',
    'Growth Hormone Secretagogue',
    2,
    'A potent GH secretagogue, releasing more GH than GHRP-6 with less appetite stimulation.',
    ARRAY['Strong GH release','Moderate appetite increase (less than GHRP-6)','Muscle preservation','Fat loss support'],
    ARRAY['Cortisol elevation','Prolactin elevation','Water retention','Lethargy'],
    ARRAY['Monitor cortisol and prolactin','Cycle use'],
    '[]'::jsonb,
    '100mcg 3x daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/8883203/']
),
(
    'Hexarelin',
    'Growth Hormone Secretagogue',
    70,
    'The strongest of the GHRPs for GH release, but prone to rapid desensitization.',
    ARRAY['Massive GH pulse','Potential cardioprotective effects','Muscle strength gains','Fat loss'],
    ARRAY['High prolactin spike','Cortisol spike','Water retention','Carpal tunnel symptoms'],
    ARRAY['Short cycle only','Monitor heart health (beneficial but potent)'],
    '[]'::jsonb,
    '100-200mcg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/9583277/']
),
(
    'PEG-MGF',
    'Growth & Muscle',
    48,
    'Pegylated Mechano Growth Factor, a variant of IGF-1 that promotes satellite cell activation and muscle repair.',
    ARRAY['Localized muscle growth (site enhancement)','Satellite cell activation','Systemic recovery','Neuroprotection'],
    ARRAY['Hypoglycemia (mild risk)','Injection site pain','Itchiness'],
    ARRAY['Do not use pre-workout','Potential for hypoglycemia'],
    '[]'::jsonb,
    '200-400mcg post-workout',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/22020228/']
),
(
    'Cagrilintide',
    'Weight Loss (Amylin)',
    7,
    'A long-acting amylin analog that suppresses appetite via a different pathway than GLP-1s. Often combined with Semaglutide (CagriSema).',
    ARRAY['Potent satiety signaling','Significant weight loss','Synergistic effect with GLP-1s','Slower gastric emptying'],
    ARRAY['Nausea (common)','Vomiting','Reduced appetite'],
    ARRAY['Monitor caloric intake','Stay hydrated'],
    '[]'::jsonb,
    '0.3mg - 2.4mg weekly',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/36024982/']
),
(
    'Mazdutide',
    'Dual GLP-1/Glucagon Agonist',
    NULL,
    'A dual agonist of GLP-1 and Glucagon receptors, designed to promote weight loss and energy expenditure.',
    ARRAY['High weight loss potential','Increases energy expenditure','Reduces liver fat'],
    ARRAY['Increased heart rate','Nausea','Arrhythmia risk (theoretical)'],
    ARRAY['Monitor heart rate closely','Monitor blood glucose'],
    '[]'::jsonb,
    '3mg - 9mg weekly (Trial)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/35504283/']
),
(
    'Humanin',
    'Mitochondrial',
    NULL,
    'A mitochondrial-derived peptide with potent cytoprotective, metabolic, and neuroprotective effects.',
    ARRAY['Mitochondrial biogenesis','Protects against oxidative stress','Improves insulin sensitivity','Neuroprotection (Alzheimer''s research)'],
    ARRAY['Little known side effects','Injection site pain'],
    ARRAY['May inhibit apoptosis (theoretical cancer risk in existing tumors)','Short term use recommended'],
    '[]'::jsonb,
    '2-5mg daily (Short cycles)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/11373683/']
),
(
    'B7-33',
    'Healing & Fibrosis',
    NULL,
    'A functionally selective relaxin analog designed to reduce fibrosis (scar tissue) without the side effects of native relaxin.',
    ARRAY['Reduces fibrosis / scar tissue','Does not dilate blood vessels (unlike Relaxin)','Heart failure research','Anti-inflammatory'],
    ARRAY['Mild irritation'],
    ARRAY['Effects on connective tissue integrity'],
    '[]'::jsonb,
    '1-2mg daily (split doses)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/27018318/']
),
(
    'Pinealon',
    'Bioregulator (Brain)',
    NULL,
    'A synthetic tripeptide bioregulator for the brain, noted for correction of brain function and jet lag.',
    ARRAY['Improves cognitive function','Regulates circadian rhythm','Neuroprotection','Reduces oxidative stress in brain'],
    ARRAY['None reported typically'],
    ARRAY['None specific'],
    '[]'::jsonb,
    '5-10mg daily (Oral/SubQ) for 10-20 days',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/17552093/']
),
(
    'Vilon',
    'Bioregulator (Immune)',
    NULL,
    'A synthetic dipeptide bioregulator of the thymus, stimulating immune function and regeneration.',
    ARRAY['Immune modulation','Thymus regeneration','Reduced inflammation','Anti-aging'],
    ARRAY['None reported typically'],
    ARRAY['Immune stimulation caution (autoimmune)'],
    '[]'::jsonb,
    '10mg daily course',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/12577695/']
),
(
    'Vesugen',
    'Bioregulator (Vascular)',
    NULL,
    'A tripeptide bioregulator for the vascular system, promoting blood vessel health.',
    ARRAY['Improves circulation','Strengthens vessel walls','Atherosclerosis prevention','Blood pressure normalization support'],
    ARRAY['None reported'],
    ARRAY['Check blood pressure'],
    '[]'::jsonb,
    '10mg daily course',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/18314644/']
),
(
    'Snap-8',
    'Cosmetic Peptide',
    NULL,
    'An octapeptide that reduces the depth of wrinkles caused by facial muscle contractions (Botox-like effect).',
    ARRAY['Reduces expression lines','Non-invasive','Safe alternative to Botox'],
    ARRAY['Skin irritation (rare)'],
    ARRAY['For external use only'],
    '[]'::jsonb,
    '3-10% topical concentration',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/19056056/']
),
(
    'Argireline',
    'Cosmetic Peptide',
    NULL,
    'Acetyle Hexapeptide-3/8, known as "Botox in a jar", inhibits neurotransmitter release to relax facial muscles.',
    ARRAY['Reduces forehead lines/crow''s feet','Moisturizing properties','Non-toxic'],
    ARRAY['Skin irritation','Redness'],
    ARRAY['Topical use only'],
    '[]'::jsonb,
    '5-10% topical concentration',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/18498523/']
),
(
    'Gonadorelin',
    'Hormone Support',
    10,
    'Synthetic GnRH used to stimulate the pituitary to release LH and FSH, restoring testosterone production.',
    ARRAY['Restores HPTA axis function','Increases testosterone','Preserves testicular size','Fertility support'],
    ARRAY['Hot flashes','Headache','Desensitization if dosed continuously (castration effect)'],
    ARRAY['Dosing timing is critical','Overuse leads to shutdown'],
    '[]'::jsonb,
    '100mcg pulsatile (specific protocols)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/458359/']
),
(
    'Orexin A',
    'Nootropic & Wakefulness',
    NULL,
    'A neuropeptide that regulates arousal, wakefulness, and appetite. Used for narcolepsy and fatigue.',
    ARRAY['Promotes wakefulness','Improves cognitive performance','Combats sleep deprivation effects'],
    ARRAY['Anxiety','Insomnia','Increased appetite'],
    ARRAY['Do not use if prone to anxiety','Will disrupt sleep'],
    '[]'::jsonb,
    'Intranasal (variable)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/9491897/']
),
(
    'Larazotide (AT-1001)',
    'Gut Health',
    NULL,
    'A tight junction regulator peptide that reduces intestinal permeability (leaky gut).',
    ARRAY['Reduces gut permeability','Helps with Celiac symptoms','Systemic inflammation reduction'],
    ARRAY['Mild GI upset','Headache'],
    ARRAY['Not a cure for Celiac (still need gluten free diet)'],
    '[]'::jsonb,
    '0.5mg - 2mg Oral',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/22902773/']
),
(
    'Adipotide',
    'Fat Loss (Experimental)',
    NULL,
    'A pro-apoptotic peptide that targets blood supply of white fat cells, causing them to die.',
    ARRAY['Rapid, massive fat loss (in animals)'],
    ARRAY['Kidney toxicity (Major risk)','Dehydration','Lesions'],
    ARRAY['Known to cause kidney lesions in monkeys','EXTREME CAUTION required'],
    '[]'::jsonb,
    'Highly experimental',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/22020228/']
),
(
    'Tesofensine',
    'Metabolic Agent (Research)',
    9,
    'A serotonin-noradrenaline-dopamine reuptake inhibitor originally for Parkinson''s/Alzheimer''s, now produced for weight loss.',
    ARRAY['Powerful appetite suppression','Increased metabolic rate','Mood enhancement'],
    ARRAY['Insomnia','Dry mouth','Elevated heart rate','Anxiety','Constipation'],
    ARRAY['Monitor blood pressure and heart rate','Taper off slowly'],
    '[]'::jsonb,
    '0.25mg - 0.5mg daily (Oral)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/18974309/']
),
(
    'Cardarine (GW-501516)',
    'Performance / PPAR',
    12,
    'A PPAR-delta agonist that switches energy preference from glucose to lipids, enhancing endurance and fat loss.',
    ARRAY['Massive endurance boost','Fat burning','Improved lipid profile (raises HDL, lowers LDL)'],
    ARRAY['None acute usually','Cancer risk (black box - controversial animal studies)'],
    ARRAY['Potential carcinogen in long term/high dose use','Use at own risk'],
    '[]'::jsonb,
    '10-20mg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/15138255/']
),
(
    'Stenabolic (SR-9009)',
    'Performance / Rev-ErbA',
    4,
    'A Rev-ErbA agonist that affects circadian rhythm and metabolism, often called "exercise in a bottle".',
    ARRAY['Endurance increase','Metabolic boost','Reduced cholesterol','Decreased anxiety'],
    ARRAY['Insomnia','Wakefulness'],
    ARRAY['Timing matters (can disrupt sleep)'],
    '[]'::jsonb,
    '10-30mg daily (dosed 3-4x)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/22460951/']
),
(
    'Enclomiphene',
    'Hormone Support (SERM)',
    10,
    'The preferred isomer of Clomid, antagonizing estrogen at the pituitary to stimulate natural testosterone production without estrogenic side effects of zuclomiphene.',
    ARRAY['Raises natural testosterone','Maintains fertility','Fewer emotional side effects than Clomid'],
    ARRAY['Reduced IGF-1 levels','Vision changes (floaters) - rare but serious','Libido variance'],
    ARRAY['Stop if vision changes occur','Monitor Estradiol'],
    '[]'::jsonb,
    '6.25mg - 25mg daily',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/24369076/']
),
(
    'NA-Semax Amidate',
    'Nootropic (Advanced)',
    NULL,
    'Acetylated and amidated version of Semax for improved stability, blood-brain barrier penetration, and potency.',
    ARRAY['Stronger focus than regular Semax','Longer duration','Neuroprotection','Mental clarity'],
    ARRAY['Overstimulation','Headache','Irritability'],
    ARRAY['Start low dose','Keep refrigerated'],
    '[]'::jsonb,
    '200-600mcg daily (Nasal)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/16996699/']
),
(
    'NA-Selank Amidate',
    'Anxiolytic (Advanced)',
    NULL,
    'Acetylated and amidated Selank, offering enhanced potency and duration for anxiety relief.',
    ARRAY['Potent anxiety reduction','No sedation','Mood elevation','Immune modulation'],
    ARRAY['Lethargy (at high doses)','Brain fog'],
    ARRAY['Keep refrigerated'],
    '[]'::jsonb,
    '200-600mcg daily (Nasal)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/18577961/']
),
(
    'ACE-031',
    'Muscle Growth (Myostatin)',
    10,
    'A soluble fusion protein that binds to myostatin and other negative muscle regulators, preventing them from acting.',
    ARRAY['Explosive muscle growth','Fat loss'],
    ARRAY['Nose bleeds (common in trials)','Gum bleeding','Telangiectasia (dilated blood vessels)'],
    ARRAY['Do not use; known safety issues in trials','Monitor mucosal bleeding'],
    '[]'::jsonb,
    '1mg/kg (Experimental)',
    ARRAY['https://pubmed.ncbi.nlm.nih.gov/23168536/']
)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    half_life_hours = EXCLUDED.half_life_hours,
    description = EXCLUDED.description,
    benefits = EXCLUDED.benefits,
    side_effects = EXCLUDED.side_effects,
    warnings = EXCLUDED.warnings,
    dosage_protocols = EXCLUDED.dosage_protocols,
    common_dosage = EXCLUDED.common_dosage,
    research_links = EXCLUDED.research_links;